# Nombre del microservicio y puerto (evita choque con otros ms)
spring.application.name=producto_ms
server.port=8086

# Conexion a MySQL (ajusta BD/usuario/clave segun tu entorno)
spring.datasource.url=jdbc:mysql://localhost:3306/producto_ms?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=tu_password

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect