spring.application.name=categorias_ms

# Puerto del microservicio Categorias
server.port=8081

# Base de datos del microservicio Categorias
spring.datasource.url=jdbc:mysql://localhost:3306/categorias_ms?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Basic Auth
spring.security.user.name=admin
spring.security.user.password=admin123

# Logs propios
logging.file.name=logs/categorias_ms.log
logging.level.root=INFO
logging.level.com.example.categorias_ms=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n