# Nombre y puerto del microservicio
spring.application.name=pago_ms
server.port=8084

# Conexion a MySQL (ajusta host, puerto, bd, usuario y clave)
spring.datasource.url=jdbc:mysql://localhost:3306/pago_ms?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=tu_password

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto MySQL (recomendado para evitar warnings)
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect